package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Account".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class AccountCursor extends Cursor<Account> {
    @Internal
    static final class Factory implements CursorFactory<Account> {
        @Override
        public Cursor<Account> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new AccountCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Account_.AccountIdGetter ID_GETTER = Account_.__ID_GETTER;

    private final LocalDateTimeConverter createdDateConverter = new LocalDateTimeConverter();

    private final static int __ID_accNumber = Account_.accNumber.id;
    private final static int __ID_title = Account_.title.id;
    private final static int __ID_titleAr = Account_.titleAr.id;
    private final static int __ID_createdDate = Account_.createdDate.id;
    private final static int __ID_balance = Account_.balance.id;
    private final static int __ID_branchId = Account_.branchId.id;

    public AccountCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Account_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Account entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Account entity) {
        String accNumber = entity.accNumber;
        int __id1 = accNumber != null ? __ID_accNumber : 0;
        String title = entity.title;
        int __id2 = title != null ? __ID_title : 0;
        String titleAr = entity.titleAr;
        int __id3 = titleAr != null ? __ID_titleAr : 0;
        String branchId = entity.branchId;
        int __id6 = branchId != null ? __ID_branchId : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, accNumber, __id2, title,
                __id3, titleAr, __id6, branchId);

        LocalDateTime createdDate = entity.createdDate;
        int __id4 = createdDate != null ? __ID_createdDate : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, null, 0, null,
                0, null, 0, null,
                __id4, __id4 != 0 ? createdDateConverter.convertToDatabaseValue(createdDate) : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, __ID_balance, entity.balance);

        entity.id = __assignedId;

        return __assignedId;
    }

}
