
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.CategoryCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Category". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Category_ implements EntityInfo<Category> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Category";

    public static final int __ENTITY_ID = 20;

    public static final Class<Category> __ENTITY_CLASS = Category.class;

    public static final String __DB_NAME = "Category";

    public static final CursorFactory<Category> __CURSOR_FACTORY = new Factory();

    @Internal
    static final CategoryIdGetter __ID_GETTER = new CategoryIdGetter();

    public final static Category_ __INSTANCE = new Category_();

    public final static io.objectbox.Property<Category> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Category> title =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "title");

    public final static io.objectbox.Property<Category> description =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "description");

    public final static io.objectbox.Property<Category> createdDate =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, long.class, "createdDate", false, "createdDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Category> image =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, byte[].class, "image");

    public final static io.objectbox.Property<Category> branchId =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "branchId");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Category>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        title,
        description,
        createdDate,
        image,
        branchId
    };

    public final static io.objectbox.Property<Category> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Category> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Category>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Category> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Category> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Category> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class CategoryIdGetter implements IdGetter<Category> {
        @Override
        public long getId(Category object) {
            return object.id;
        }
    }

}
