
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.objectbox.model.DeliveryCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Delivery". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Delivery_ implements EntityInfo<Delivery> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Delivery";

    public static final int __ENTITY_ID = 22;

    public static final Class<Delivery> __ENTITY_CLASS = Delivery.class;

    public static final String __DB_NAME = "Delivery";

    public static final CursorFactory<Delivery> __CURSOR_FACTORY = new Factory();

    @Internal
    static final DeliveryIdGetter __ID_GETTER = new DeliveryIdGetter();

    public final static Delivery_ __INSTANCE = new Delivery_();

    public final static io.objectbox.Property<Delivery> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Delivery> name =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "name");

    public final static io.objectbox.Property<Delivery> phoneNumber =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "phoneNumber");

    public final static io.objectbox.Property<Delivery> image =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, byte[].class, "image");

    public final static io.objectbox.Property<Delivery> location =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "location");

    public final static io.objectbox.Property<Delivery> deliveryBy =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, int.class, "deliveryBy");

    public final static io.objectbox.Property<Delivery> priority =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, int.class, "priority");

    public final static io.objectbox.Property<Delivery> isActive =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, boolean.class, "isActive");

    public final static io.objectbox.Property<Delivery> branchId =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, String.class, "branchId");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Delivery>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        name,
        phoneNumber,
        image,
        location,
        deliveryBy,
        priority,
        isActive,
        branchId
    };

    public final static io.objectbox.Property<Delivery> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Delivery> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Delivery>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Delivery> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Delivery> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Delivery> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class DeliveryIdGetter implements IdGetter<Delivery> {
        @Override
        public long getId(Delivery object) {
            return object.id;
        }
    }

}
