package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Entry".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class EntryCursor extends Cursor<Entry> {
    @Internal
    static final class Factory implements CursorFactory<Entry> {
        @Override
        public Cursor<Entry> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new EntryCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Entry_.EntryIdGetter ID_GETTER = Entry_.__ID_GETTER;

    private final LocalDateTimeConverter createdDateConverter = new LocalDateTimeConverter();

    private final static int __ID_entryAmount = Entry_.entryAmount.id;
    private final static int __ID_entryNote = Entry_.entryNote.id;
    private final static int __ID_branchId = Entry_.branchId.id;
    private final static int __ID_createdDate = Entry_.createdDate.id;

    public EntryCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Entry_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Entry entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Entry entity) {
        String entryNote = entity.entryNote;
        int __id2 = entryNote != null ? __ID_entryNote : 0;
        String branchId = entity.branchId;
        int __id3 = branchId != null ? __ID_branchId : 0;
        LocalDateTime createdDate = entity.createdDate;
        int __id4 = createdDate != null ? __ID_createdDate : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id2, entryNote, __id3, branchId,
                0, null, 0, null,
                __id4, __id4 != 0 ? createdDateConverter.convertToDatabaseValue(createdDate) : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, __ID_entryAmount, entity.entryAmount);

        entity.id = __assignedId;

        return __assignedId;
    }

}
