
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.EntryCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Entry". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Entry_ implements EntityInfo<Entry> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Entry";

    public static final int __ENTITY_ID = 23;

    public static final Class<Entry> __ENTITY_CLASS = Entry.class;

    public static final String __DB_NAME = "Entry";

    public static final CursorFactory<Entry> __CURSOR_FACTORY = new Factory();

    @Internal
    static final EntryIdGetter __ID_GETTER = new EntryIdGetter();

    public final static Entry_ __INSTANCE = new Entry_();

    public final static io.objectbox.Property<Entry> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Entry> entryAmount =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, double.class, "entryAmount");

    public final static io.objectbox.Property<Entry> entryNote =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "entryNote");

    public final static io.objectbox.Property<Entry> branchId =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "branchId");

    public final static io.objectbox.Property<Entry> createdDate =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, long.class, "createdDate", false, "createdDate", LocalDateTimeConverter.class, LocalDateTime.class);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Entry>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        entryAmount,
        entryNote,
        branchId,
        createdDate
    };

    public final static io.objectbox.Property<Entry> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Entry> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Entry>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Entry> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Entry> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Entry> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class EntryIdGetter implements IdGetter<Entry> {
        @Override
        public long getId(Entry object) {
            return object.id;
        }
    }

}
