
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.objectbox.model.InvoiceCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Invoice". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Invoice_ implements EntityInfo<Invoice> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Invoice";

    public static final int __ENTITY_ID = 24;

    public static final Class<Invoice> __ENTITY_CLASS = Invoice.class;

    public static final String __DB_NAME = "Invoice";

    public static final CursorFactory<Invoice> __CURSOR_FACTORY = new Factory();

    @Internal
    static final InvoiceIdGetter __ID_GETTER = new InvoiceIdGetter();

    public final static Invoice_ __INSTANCE = new Invoice_();

    public final static io.objectbox.Property<Invoice> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Invoice> invNum =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "invNum");

    public final static io.objectbox.Property<Invoice> amountFrom =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, double.class, "amountFrom");

    public final static io.objectbox.Property<Invoice> amountTo =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, double.class, "amountTo");

    public final static io.objectbox.Property<Invoice> taxRate =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, double.class, "taxRate");

    public final static io.objectbox.Property<Invoice> note =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "note");

    public final static io.objectbox.Property<Invoice> branchId =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, String.class, "branchId");

    public final static io.objectbox.Property<Invoice> createdDate =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, java.util.Date.class, "createdDate");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Invoice>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        invNum,
        amountFrom,
        amountTo,
        taxRate,
        note,
        branchId,
        createdDate
    };

    public final static io.objectbox.Property<Invoice> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Invoice> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Invoice>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Invoice> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Invoice> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Invoice> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class InvoiceIdGetter implements IdGetter<Invoice> {
        @Override
        public long getId(Invoice object) {
            return object.getId();
        }
    }

}
