package com.irestaurant.iPortalAPI.objectbox.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Invoice".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class InvoiceCursor extends Cursor<Invoice> {
    @Internal
    static final class Factory implements CursorFactory<Invoice> {
        @Override
        public Cursor<Invoice> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new InvoiceCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Invoice_.InvoiceIdGetter ID_GETTER = Invoice_.__ID_GETTER;


    private final static int __ID_invNum = Invoice_.invNum.id;
    private final static int __ID_amountFrom = Invoice_.amountFrom.id;
    private final static int __ID_amountTo = Invoice_.amountTo.id;
    private final static int __ID_taxRate = Invoice_.taxRate.id;
    private final static int __ID_note = Invoice_.note.id;
    private final static int __ID_branchId = Invoice_.branchId.id;
    private final static int __ID_createdDate = Invoice_.createdDate.id;

    public InvoiceCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Invoice_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Invoice entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Invoice entity) {
        String invNum = entity.getInvNum();
        int __id1 = invNum != null ? __ID_invNum : 0;
        String note = entity.getNote();
        int __id5 = note != null ? __ID_note : 0;
        String branchId = entity.getBranchId();
        int __id6 = branchId != null ? __ID_branchId : 0;
        java.util.Date createdDate = entity.getCreatedDate();
        int __id7 = createdDate != null ? __ID_createdDate : 0;

        collect313311(cursor, 0, PUT_FLAG_FIRST,
                __id1, invNum, __id5, note,
                __id6, branchId, 0, null,
                __id7, __id7 != 0 ? createdDate.getTime() : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, __ID_amountFrom, entity.getAmountFrom());

        long __assignedId = collect002033(cursor, entity.getId(), PUT_FLAG_COMPLETE,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, __ID_amountTo, entity.getAmountTo(),
                __ID_taxRate, entity.getTaxRate(), 0, 0);

        entity.setId(__assignedId);

        return __assignedId;
    }

}
