
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.objectbox.model.KitchenCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Kitchen". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Kitchen_ implements EntityInfo<Kitchen> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Kitchen";

    public static final int __ENTITY_ID = 25;

    public static final Class<Kitchen> __ENTITY_CLASS = Kitchen.class;

    public static final String __DB_NAME = "Kitchen";

    public static final CursorFactory<Kitchen> __CURSOR_FACTORY = new Factory();

    @Internal
    static final KitchenIdGetter __ID_GETTER = new KitchenIdGetter();

    public final static Kitchen_ __INSTANCE = new Kitchen_();

    public final static io.objectbox.Property<Kitchen> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Kitchen> title =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "title");

    public final static io.objectbox.Property<Kitchen> description =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "description");

    public final static io.objectbox.Property<Kitchen> image =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, byte[].class, "image");

    public final static io.objectbox.Property<Kitchen> branchId =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "branchId");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Kitchen>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        title,
        description,
        image,
        branchId
    };

    public final static io.objectbox.Property<Kitchen> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Kitchen> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Kitchen>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Kitchen> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Kitchen> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Kitchen> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class KitchenIdGetter implements IdGetter<Kitchen> {
        @Override
        public long getId(Kitchen object) {
            return object.id;
        }
    }

}
