
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.LogEventCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "LogEvent". Can be used for QueryBuilder and for referencing DB names.
 */
public final class LogEvent_ implements EntityInfo<LogEvent> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "LogEvent";

    public static final int __ENTITY_ID = 26;

    public static final Class<LogEvent> __ENTITY_CLASS = LogEvent.class;

    public static final String __DB_NAME = "LogEvent";

    public static final CursorFactory<LogEvent> __CURSOR_FACTORY = new Factory();

    @Internal
    static final LogEventIdGetter __ID_GETTER = new LogEventIdGetter();

    public final static LogEvent_ __INSTANCE = new LogEvent_();

    public final static io.objectbox.Property<LogEvent> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<LogEvent> logEvent =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, int.class, "logEvent");

    public final static io.objectbox.Property<LogEvent> createdDate =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, long.class, "createdDate", false, "createdDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<LogEvent> branchId =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "branchId");

    public final static io.objectbox.Property<LogEvent> args =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, java.util.List.class, "args");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<LogEvent>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        logEvent,
        createdDate,
        branchId,
        args
    };

    public final static io.objectbox.Property<LogEvent> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<LogEvent> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<LogEvent>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<LogEvent> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<LogEvent> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<LogEvent> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class LogEventIdGetter implements IdGetter<LogEvent> {
        @Override
        public long getId(LogEvent object) {
            return object.id;
        }
    }

}
