package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import java.time.LocalDateTime;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "LogEvent".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class LogEventCursor extends Cursor<LogEvent> {
    @Internal
    static final class Factory implements CursorFactory<LogEvent> {
        @Override
        public Cursor<LogEvent> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new LogEventCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final LogEvent_.LogEventIdGetter ID_GETTER = LogEvent_.__ID_GETTER;

    private final LocalDateTimeConverter createdDateConverter = new LocalDateTimeConverter();

    private final static int __ID_logEvent = LogEvent_.logEvent.id;
    private final static int __ID_createdDate = LogEvent_.createdDate.id;
    private final static int __ID_branchId = LogEvent_.branchId.id;
    private final static int __ID_args = LogEvent_.args.id;

    public LogEventCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, LogEvent_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(LogEvent entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(LogEvent entity) {
        java.util.List<String> args = entity.args;
        int __id4 = args != null ? __ID_args : 0;

        collectStringList(cursor, 0, PUT_FLAG_FIRST,
                __id4, args);

        String branchId = entity.branchId;
        int __id3 = branchId != null ? __ID_branchId : 0;
        LocalDateTime createdDate = entity.createdDate;
        int __id2 = createdDate != null ? __ID_createdDate : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                __id3, branchId, 0, null,
                0, null, 0, null,
                __id2, __id2 != 0 ? createdDateConverter.convertToDatabaseValue(createdDate) : 0, __ID_logEvent, entity.logEvent,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
