package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import java.time.LocalDateTime;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Notification".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class NotificationCursor extends Cursor<Notification> {
    @Internal
    static final class Factory implements CursorFactory<Notification> {
        @Override
        public Cursor<Notification> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new NotificationCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Notification_.NotificationIdGetter ID_GETTER = Notification_.__ID_GETTER;

    private final LocalDateTimeConverter creationDateConverter = new LocalDateTimeConverter();

    private final static int __ID_title = Notification_.title.id;
    private final static int __ID_subtitle = Notification_.subtitle.id;
    private final static int __ID_branchId = Notification_.branchId.id;
    private final static int __ID_badgeCount = Notification_.badgeCount.id;
    private final static int __ID_canReply = Notification_.canReply.id;
    private final static int __ID_creationDate = Notification_.creationDate.id;
    private final static int __ID_type = Notification_.type.id;
    private final static int __ID_usecase = Notification_.usecase.id;

    public NotificationCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Notification_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Notification entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Notification entity) {
        String title = entity.title;
        int __id1 = title != null ? __ID_title : 0;
        String subtitle = entity.subtitle;
        int __id2 = subtitle != null ? __ID_subtitle : 0;
        String branchId = entity.branchId;
        int __id3 = branchId != null ? __ID_branchId : 0;
        LocalDateTime creationDate = entity.creationDate;
        int __id6 = creationDate != null ? __ID_creationDate : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, title, __id2, subtitle,
                __id3, branchId, 0, null,
                __id6, __id6 != 0 ? creationDateConverter.convertToDatabaseValue(creationDate) : 0, __ID_badgeCount, entity.badgeCount,
                __ID_type, entity.type, __ID_usecase, entity.usecase,
                __ID_canReply, entity.canReply ? 1 : 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
