
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.NotificationMessageCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "NotificationMessage". Can be used for QueryBuilder and for referencing DB names.
 */
public final class NotificationMessage_ implements EntityInfo<NotificationMessage> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "NotificationMessage";

    public static final int __ENTITY_ID = 28;

    public static final Class<NotificationMessage> __ENTITY_CLASS = NotificationMessage.class;

    public static final String __DB_NAME = "NotificationMessage";

    public static final CursorFactory<NotificationMessage> __CURSOR_FACTORY = new Factory();

    @Internal
    static final NotificationMessageIdGetter __ID_GETTER = new NotificationMessageIdGetter();

    public final static NotificationMessage_ __INSTANCE = new NotificationMessage_();

    public final static io.objectbox.Property<NotificationMessage> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<NotificationMessage> title =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "title");

    public final static io.objectbox.Property<NotificationMessage> message =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "message");

    public final static io.objectbox.Property<NotificationMessage> creationDate =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, long.class, "creationDate", false, "creationDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<NotificationMessage> usecase =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, int.class, "usecase");

    public final static io.objectbox.Property<NotificationMessage> messageStatus =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, int.class, "messageStatus");

    public final static io.objectbox.Property<NotificationMessage> branchId =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, String.class, "branchId");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<NotificationMessage>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        title,
        message,
        creationDate,
        usecase,
        messageStatus,
        branchId
    };

    public final static io.objectbox.Property<NotificationMessage> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<NotificationMessage> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<NotificationMessage>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<NotificationMessage> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<NotificationMessage> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<NotificationMessage> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class NotificationMessageIdGetter implements IdGetter<NotificationMessage> {
        @Override
        public long getId(NotificationMessage object) {
            return object.id;
        }
    }

}
