
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.NotificationCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Notification". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Notification_ implements EntityInfo<Notification> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Notification";

    public static final int __ENTITY_ID = 27;

    public static final Class<Notification> __ENTITY_CLASS = Notification.class;

    public static final String __DB_NAME = "Notification";

    public static final CursorFactory<Notification> __CURSOR_FACTORY = new Factory();

    @Internal
    static final NotificationIdGetter __ID_GETTER = new NotificationIdGetter();

    public final static Notification_ __INSTANCE = new Notification_();

    public final static io.objectbox.Property<Notification> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Notification> title =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "title");

    public final static io.objectbox.Property<Notification> subtitle =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "subtitle");

    public final static io.objectbox.Property<Notification> branchId =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "branchId");

    public final static io.objectbox.Property<Notification> badgeCount =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, int.class, "badgeCount");

    public final static io.objectbox.Property<Notification> canReply =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, boolean.class, "canReply");

    public final static io.objectbox.Property<Notification> creationDate =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, long.class, "creationDate", false, "creationDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Notification> type =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, int.class, "type");

    public final static io.objectbox.Property<Notification> usecase =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, int.class, "usecase");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Notification>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        title,
        subtitle,
        branchId,
        badgeCount,
        canReply,
        creationDate,
        type,
        usecase
    };

    public final static io.objectbox.Property<Notification> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Notification> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Notification>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Notification> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Notification> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Notification> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class NotificationIdGetter implements IdGetter<Notification> {
        @Override
        public long getId(Notification object) {
            return object.id;
        }
    }

}
