package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;
import java.time.LocalDateTime;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Order".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class OrderCursor extends Cursor<Order> {
    @Internal
    static final class Factory implements CursorFactory<Order> {
        @Override
        public Cursor<Order> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new OrderCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Order_.OrderIdGetter ID_GETTER = Order_.__ID_GETTER;

    private final LocalDateTimeConverter createdDateConverter = new LocalDateTimeConverter();
    private final LocalDateTimeConverter modifiedDateConverter = new LocalDateTimeConverter();
    private final LocalDateTimeConverter inPreparationDateConverter = new LocalDateTimeConverter();
    private final LocalDateTimeConverter readyDateConverter = new LocalDateTimeConverter();
    private final LocalDateTimeConverter deliveredDateConverter = new LocalDateTimeConverter();
    private final LocalDateTimeConverter cancelledDateConverter = new LocalDateTimeConverter();

    private final static int __ID_orderNumber = Order_.orderNumber.id;
    private final static int __ID_createdDate = Order_.createdDate.id;
    private final static int __ID_modifiedDate = Order_.modifiedDate.id;
    private final static int __ID_inPreparationDate = Order_.inPreparationDate.id;
    private final static int __ID_readyDate = Order_.readyDate.id;
    private final static int __ID_deliveredDate = Order_.deliveredDate.id;
    private final static int __ID_cancelledDate = Order_.cancelledDate.id;
    private final static int __ID_orderType = Order_.orderType.id;
    private final static int __ID_orderStatus = Order_.orderStatus.id;
    private final static int __ID_paymentMethod = Order_.paymentMethod.id;
    private final static int __ID_preparationTime = Order_.preparationTime.id;
    private final static int __ID_notes = Order_.notes.id;
    private final static int __ID_doneNotes = Order_.doneNotes.id;
    private final static int __ID_stopNote = Order_.stopNote.id;
    private final static int __ID_branchId = Order_.branchId.id;
    private final static int __ID_customerId = Order_.customerId.id;
    private final static int __ID_userId = Order_.userId.id;
    private final static int __ID_tableId = Order_.tableId.id;
    private final static int __ID_deliveryId = Order_.deliveryId.id;

    public OrderCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Order_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Order entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Order entity) {
        ToOne<Customer> customer = entity.customer;
        if(customer != null && customer.internalRequiresPutTarget()) {
            Cursor<Customer> targetCursor = getRelationTargetCursor(Customer.class);
            try {
                customer.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<User> user = entity.user;
        if(user != null && user.internalRequiresPutTarget()) {
            Cursor<User> targetCursor = getRelationTargetCursor(User.class);
            try {
                user.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<Table> table = entity.table;
        if(table != null && table.internalRequiresPutTarget()) {
            Cursor<Table> targetCursor = getRelationTargetCursor(Table.class);
            try {
                table.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<Delivery> delivery = entity.delivery;
        if(delivery != null && delivery.internalRequiresPutTarget()) {
            Cursor<Delivery> targetCursor = getRelationTargetCursor(Delivery.class);
            try {
                delivery.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String orderNumber = entity.orderNumber;
        int __id1 = orderNumber != null ? __ID_orderNumber : 0;
        String notes = entity.notes;
        int __id12 = notes != null ? __ID_notes : 0;
        String doneNotes = entity.doneNotes;
        int __id13 = doneNotes != null ? __ID_doneNotes : 0;
        String stopNote = entity.stopNote;
        int __id14 = stopNote != null ? __ID_stopNote : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, orderNumber, __id12, notes,
                __id13, doneNotes, __id14, stopNote);

        String branchId = entity.branchId;
        int __id15 = branchId != null ? __ID_branchId : 0;
        LocalDateTime createdDate = entity.createdDate;
        int __id2 = createdDate != null ? __ID_createdDate : 0;
        LocalDateTime modifiedDate = entity.modifiedDate;
        int __id3 = modifiedDate != null ? __ID_modifiedDate : 0;
        LocalDateTime inPreparationDate = entity.inPreparationDate;
        int __id4 = inPreparationDate != null ? __ID_inPreparationDate : 0;

        collect313311(cursor, 0, 0,
                __id15, branchId, 0, null,
                0, null, 0, null,
                __id2, __id2 != 0 ? createdDateConverter.convertToDatabaseValue(createdDate) : 0, __id3, __id3 != 0 ? modifiedDateConverter.convertToDatabaseValue(modifiedDate) : 0,
                __id4, __id4 != 0 ? inPreparationDateConverter.convertToDatabaseValue(inPreparationDate) : 0, __ID_orderType, entity.orderType,
                __ID_orderStatus, entity.orderStatus, __ID_paymentMethod, entity.paymentMethod,
                0, 0, 0, 0);

        LocalDateTime readyDate = entity.readyDate;
        int __id5 = readyDate != null ? __ID_readyDate : 0;
        LocalDateTime deliveredDate = entity.deliveredDate;
        int __id6 = deliveredDate != null ? __ID_deliveredDate : 0;
        LocalDateTime cancelledDate = entity.cancelledDate;
        int __id7 = cancelledDate != null ? __ID_cancelledDate : 0;

        collect313311(cursor, 0, 0,
                0, null, 0, null,
                0, null, 0, null,
                __id5, __id5 != 0 ? readyDateConverter.convertToDatabaseValue(readyDate) : 0, __id6, __id6 != 0 ? deliveredDateConverter.convertToDatabaseValue(deliveredDate) : 0,
                __id7, __id7 != 0 ? cancelledDateConverter.convertToDatabaseValue(cancelledDate) : 0, __ID_preparationTime, entity.preparationTime,
                0, 0, 0, 0,
                0, 0, 0, 0);

        collect313311(cursor, 0, 0,
                0, null, 0, null,
                0, null, 0, null,
                __ID_customerId, entity.customer.getTargetId(), __ID_userId, entity.user.getTargetId(),
                __ID_tableId, entity.table.getTargetId(), 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, null, 0, null,
                0, null, 0, null,
                __ID_deliveryId, entity.delivery.getTargetId(), 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        attachEntity(entity);
        checkApplyToManyToDb(entity.orderItems, OrderItem.class);
        checkApplyToManyToDb(entity.orderEntries, OrderEntry.class);
        return __assignedId;
    }

    private void attachEntity(Order entity) {
        // Transformer will create __boxStore field in entity and init it here:
        // entity.__boxStore = boxStoreForEntities;
    }

}
