package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToOne;
import java.time.LocalDateTime;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "OrderEntry".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class OrderEntryCursor extends Cursor<OrderEntry> {
    @Internal
    static final class Factory implements CursorFactory<OrderEntry> {
        @Override
        public Cursor<OrderEntry> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new OrderEntryCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final OrderEntry_.OrderEntryIdGetter ID_GETTER = OrderEntry_.__ID_GETTER;

    private final LocalDateTimeConverter dateTimeConverter = new LocalDateTimeConverter();

    private final static int __ID_orderType = OrderEntry_.orderType.id;
    private final static int __ID_dateTime = OrderEntry_.dateTime.id;
    private final static int __ID_orderNum = OrderEntry_.orderNum.id;
    private final static int __ID_branchId = OrderEntry_.branchId.id;
    private final static int __ID_orderId = OrderEntry_.orderId.id;
    private final static int __ID_deliveryId = OrderEntry_.deliveryId.id;
    private final static int __ID_waiterId = OrderEntry_.waiterId.id;

    public OrderEntryCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, OrderEntry_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(OrderEntry entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(OrderEntry entity) {
        ToOne<Order> order = entity.order;
        if(order != null && order.internalRequiresPutTarget()) {
            Cursor<Order> targetCursor = getRelationTargetCursor(Order.class);
            try {
                order.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<Delivery> delivery = entity.delivery;
        if(delivery != null && delivery.internalRequiresPutTarget()) {
            Cursor<Delivery> targetCursor = getRelationTargetCursor(Delivery.class);
            try {
                delivery.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<Waiter> waiter = entity.waiter;
        if(waiter != null && waiter.internalRequiresPutTarget()) {
            Cursor<Waiter> targetCursor = getRelationTargetCursor(Waiter.class);
            try {
                waiter.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String orderNum = entity.orderNum;
        int __id3 = orderNum != null ? __ID_orderNum : 0;
        String branchId = entity.branchId;
        int __id4 = branchId != null ? __ID_branchId : 0;
        LocalDateTime dateTime = entity.dateTime;
        int __id2 = dateTime != null ? __ID_dateTime : 0;

        collect313311(cursor, 0, PUT_FLAG_FIRST,
                __id3, orderNum, __id4, branchId,
                0, null, 0, null,
                __id2, __id2 != 0 ? dateTimeConverter.convertToDatabaseValue(dateTime) : 0, __ID_orderId, entity.order.getTargetId(),
                __ID_deliveryId, entity.delivery.getTargetId(), __ID_orderType, entity.orderType,
                0, 0, 0, 0,
                0, 0, 0, 0);

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, null, 0, null,
                0, null, 0, null,
                __ID_waiterId, entity.waiter.getTargetId(), 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        attachEntity(entity);
        return __assignedId;
    }

    private void attachEntity(OrderEntry entity) {
        // Transformer will create __boxStore field in entity and init it here:
        // entity.__boxStore = boxStoreForEntities;
    }

}
