
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.OrderCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToManyGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;
import java.time.LocalDateTime;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Order". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Order_ implements EntityInfo<Order> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Order";

    public static final int __ENTITY_ID = 29;

    public static final Class<Order> __ENTITY_CLASS = Order.class;

    public static final String __DB_NAME = "Order";

    public static final CursorFactory<Order> __CURSOR_FACTORY = new Factory();

    @Internal
    static final OrderIdGetter __ID_GETTER = new OrderIdGetter();

    public final static Order_ __INSTANCE = new Order_();

    public final static io.objectbox.Property<Order> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Order> orderNumber =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "orderNumber");

    public final static io.objectbox.Property<Order> createdDate =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, long.class, "createdDate", false, "createdDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Order> modifiedDate =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, long.class, "modifiedDate", false, "modifiedDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Order> inPreparationDate =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, long.class, "inPreparationDate", false, "inPreparationDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Order> readyDate =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, long.class, "readyDate", false, "readyDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Order> deliveredDate =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, long.class, "deliveredDate", false, "deliveredDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Order> cancelledDate =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, long.class, "cancelledDate", false, "cancelledDate", LocalDateTimeConverter.class, LocalDateTime.class);

    public final static io.objectbox.Property<Order> orderType =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, int.class, "orderType");

    public final static io.objectbox.Property<Order> orderStatus =
        new io.objectbox.Property<>(__INSTANCE, 9, 10, int.class, "orderStatus");

    public final static io.objectbox.Property<Order> paymentMethod =
        new io.objectbox.Property<>(__INSTANCE, 10, 11, int.class, "paymentMethod");

    public final static io.objectbox.Property<Order> preparationTime =
        new io.objectbox.Property<>(__INSTANCE, 11, 12, int.class, "preparationTime");

    public final static io.objectbox.Property<Order> notes =
        new io.objectbox.Property<>(__INSTANCE, 12, 13, String.class, "notes");

    public final static io.objectbox.Property<Order> doneNotes =
        new io.objectbox.Property<>(__INSTANCE, 13, 14, String.class, "doneNotes");

    public final static io.objectbox.Property<Order> stopNote =
        new io.objectbox.Property<>(__INSTANCE, 14, 15, String.class, "stopNote");

    public final static io.objectbox.Property<Order> branchId =
        new io.objectbox.Property<>(__INSTANCE, 15, 16, String.class, "branchId");

    public final static io.objectbox.Property<Order> customerId =
        new io.objectbox.Property<>(__INSTANCE, 16, 17, long.class, "customerId", true);

    public final static io.objectbox.Property<Order> userId =
        new io.objectbox.Property<>(__INSTANCE, 17, 18, long.class, "userId", true);

    public final static io.objectbox.Property<Order> tableId =
        new io.objectbox.Property<>(__INSTANCE, 18, 19, long.class, "tableId", true);

    public final static io.objectbox.Property<Order> deliveryId =
        new io.objectbox.Property<>(__INSTANCE, 19, 20, long.class, "deliveryId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Order>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        orderNumber,
        createdDate,
        modifiedDate,
        inPreparationDate,
        readyDate,
        deliveredDate,
        cancelledDate,
        orderType,
        orderStatus,
        paymentMethod,
        preparationTime,
        notes,
        doneNotes,
        stopNote,
        branchId,
        customerId,
        userId,
        tableId,
        deliveryId
    };

    public final static io.objectbox.Property<Order> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Order> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Order>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Order> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Order> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Order> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class OrderIdGetter implements IdGetter<Order> {
        @Override
        public long getId(Order object) {
            return object.id;
        }
    }

    /** To-one relation "customer" to target entity "Customer". */
    public static final RelationInfo<Order, Customer> customer =
            new RelationInfo<>(Order_.__INSTANCE, Customer_.__INSTANCE, customerId, new ToOneGetter<Order, Customer>() {
                @Override
                public ToOne<Customer> getToOne(Order entity) {
                    return entity.customer;
                }
            });

    /** To-one relation "user" to target entity "User". */
    public static final RelationInfo<Order, User> user =
            new RelationInfo<>(Order_.__INSTANCE, User_.__INSTANCE, userId, new ToOneGetter<Order, User>() {
                @Override
                public ToOne<User> getToOne(Order entity) {
                    return entity.user;
                }
            });

    /** To-one relation "table" to target entity "Table". */
    public static final RelationInfo<Order, Table> table =
            new RelationInfo<>(Order_.__INSTANCE, Table_.__INSTANCE, tableId, new ToOneGetter<Order, Table>() {
                @Override
                public ToOne<Table> getToOne(Order entity) {
                    return entity.table;
                }
            });

    /** To-one relation "delivery" to target entity "Delivery". */
    public static final RelationInfo<Order, Delivery> delivery =
            new RelationInfo<>(Order_.__INSTANCE, Delivery_.__INSTANCE, deliveryId, new ToOneGetter<Order, Delivery>() {
                @Override
                public ToOne<Delivery> getToOne(Order entity) {
                    return entity.delivery;
                }
            });

    /** To-many relation "orderItems" to target entity "OrderItem". */
    public static final RelationInfo<Order, OrderItem> orderItems = new RelationInfo<>(Order_.__INSTANCE, OrderItem_.__INSTANCE,
            new ToManyGetter<Order, OrderItem>() {
                @Override
                public List<OrderItem> getToMany(Order entity) {
                    return entity.orderItems;
                }
            },
             7);

    /** To-many relation "orderEntries" to target entity "OrderEntry". */
    public static final RelationInfo<Order, OrderEntry> orderEntries = new RelationInfo<>(Order_.__INSTANCE, OrderEntry_.__INSTANCE,
            new ToManyGetter<Order, OrderEntry>() {
                @Override
                public List<OrderEntry> getToMany(Order entity) {
                    return entity.orderEntries;
                }
            },
             8);

}
