package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Product".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class ProductCursor extends Cursor<Product> {
    @Internal
    static final class Factory implements CursorFactory<Product> {
        @Override
        public Cursor<Product> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new ProductCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Product_.ProductIdGetter ID_GETTER = Product_.__ID_GETTER;

    private final LocalDateTimeConverter createdDateConverter = new LocalDateTimeConverter();

    private final static int __ID_title = Product_.title.id;
    private final static int __ID_description = Product_.description.id;
    private final static int __ID_branchId = Product_.branchId.id;
    private final static int __ID_price = Product_.price.id;
    private final static int __ID_rating = Product_.rating.id;
    private final static int __ID_image = Product_.image.id;
    private final static int __ID_isAvailable = Product_.isAvailable.id;
    private final static int __ID_calories = Product_.calories.id;
    private final static int __ID_preparationTime = Product_.preparationTime.id;
    private final static int __ID_createdDate = Product_.createdDate.id;

    public ProductCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Product_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Product entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Product entity) {
        String title = entity.title;
        int __id1 = title != null ? __ID_title : 0;
        String description = entity.description;
        int __id2 = description != null ? __ID_description : 0;
        String branchId = entity.branchId;
        int __id3 = branchId != null ? __ID_branchId : 0;
        byte[] image = entity.image;
        int __id6 = image != null ? __ID_image : 0;
        LocalDateTime createdDate = entity.createdDate;
        int __id10 = createdDate != null ? __ID_createdDate : 0;

        collect313311(cursor, 0, PUT_FLAG_FIRST,
                __id1, title, __id2, description,
                __id3, branchId, __id6, image,
                __id10, __id10 != 0 ? createdDateConverter.convertToDatabaseValue(createdDate) : 0, __ID_preparationTime, entity.preparationTime,
                __ID_isAvailable, entity.isAvailable ? 1 : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, __ID_price, entity.price);

        long __assignedId = collect002033(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, __ID_rating, entity.rating,
                __ID_calories, entity.calories, 0, 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
