
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.converter.LocalDateTimeConverter;
import com.irestaurant.iPortalAPI.objectbox.model.ProductCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import java.time.LocalDateTime;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Product". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Product_ implements EntityInfo<Product> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Product";

    public static final int __ENTITY_ID = 32;

    public static final Class<Product> __ENTITY_CLASS = Product.class;

    public static final String __DB_NAME = "Product";

    public static final CursorFactory<Product> __CURSOR_FACTORY = new Factory();

    @Internal
    static final ProductIdGetter __ID_GETTER = new ProductIdGetter();

    public final static Product_ __INSTANCE = new Product_();

    public final static io.objectbox.Property<Product> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Product> title =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "title");

    public final static io.objectbox.Property<Product> description =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "description");

    public final static io.objectbox.Property<Product> branchId =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "branchId");

    public final static io.objectbox.Property<Product> price =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, double.class, "price");

    public final static io.objectbox.Property<Product> rating =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, double.class, "rating");

    public final static io.objectbox.Property<Product> image =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, byte[].class, "image");

    public final static io.objectbox.Property<Product> isAvailable =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, boolean.class, "isAvailable");

    public final static io.objectbox.Property<Product> calories =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, double.class, "calories");

    public final static io.objectbox.Property<Product> preparationTime =
        new io.objectbox.Property<>(__INSTANCE, 9, 10, int.class, "preparationTime");

    public final static io.objectbox.Property<Product> createdDate =
        new io.objectbox.Property<>(__INSTANCE, 10, 11, long.class, "createdDate", false, "createdDate", LocalDateTimeConverter.class, LocalDateTime.class);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Product>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        title,
        description,
        branchId,
        price,
        rating,
        image,
        isAvailable,
        calories,
        preparationTime,
        createdDate
    };

    public final static io.objectbox.Property<Product> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Product> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Product>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Product> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Product> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Product> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class ProductIdGetter implements IdGetter<Product> {
        @Override
        public long getId(Product object) {
            return object.id;
        }
    }

}
