package com.irestaurant.iPortalAPI.objectbox.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Table".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class TableCursor extends Cursor<Table> {
    @Internal
    static final class Factory implements CursorFactory<Table> {
        @Override
        public Cursor<Table> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new TableCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Table_.TableIdGetter ID_GETTER = Table_.__ID_GETTER;


    private final static int __ID_seats = Table_.seats.id;
    private final static int __ID_notes = Table_.notes.id;
    private final static int __ID_tableNumber = Table_.tableNumber.id;
    private final static int __ID_branchId = Table_.branchId.id;
    private final static int __ID_status = Table_.status.id;
    private final static int __ID_type = Table_.type.id;

    public TableCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Table_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Table entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Table entity) {
        String notes = entity.notes;
        int __id2 = notes != null ? __ID_notes : 0;
        String tableNumber = entity.tableNumber;
        int __id3 = tableNumber != null ? __ID_tableNumber : 0;
        String branchId = entity.branchId;
        int __id4 = branchId != null ? __ID_branchId : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id2, notes, __id3, tableNumber,
                __id4, branchId, 0, null,
                __ID_seats, entity.seats, __ID_status, entity.status,
                __ID_type, entity.type, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
