
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.objectbox.model.TableCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Table". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Table_ implements EntityInfo<Table> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Table";

    public static final int __ENTITY_ID = 34;

    public static final Class<Table> __ENTITY_CLASS = Table.class;

    public static final String __DB_NAME = "Table";

    public static final CursorFactory<Table> __CURSOR_FACTORY = new Factory();

    @Internal
    static final TableIdGetter __ID_GETTER = new TableIdGetter();

    public final static Table_ __INSTANCE = new Table_();

    public final static io.objectbox.Property<Table> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Table> seats =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, int.class, "seats");

    public final static io.objectbox.Property<Table> notes =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "notes");

    public final static io.objectbox.Property<Table> tableNumber =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "tableNumber");

    public final static io.objectbox.Property<Table> branchId =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "branchId");

    public final static io.objectbox.Property<Table> status =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, int.class, "status");

    public final static io.objectbox.Property<Table> type =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, int.class, "type");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Table>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        seats,
        notes,
        tableNumber,
        branchId,
        status,
        type
    };

    public final static io.objectbox.Property<Table> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Table> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Table>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Table> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Table> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Table> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class TableIdGetter implements IdGetter<Table> {
        @Override
        public long getId(Table object) {
            return object.id;
        }
    }

}
