package com.irestaurant.iPortalAPI.objectbox.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "User".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class UserCursor extends Cursor<User> {
    @Internal
    static final class Factory implements CursorFactory<User> {
        @Override
        public Cursor<User> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new UserCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final User_.UserIdGetter ID_GETTER = User_.__ID_GETTER;


    private final static int __ID_email = User_.email.id;
    private final static int __ID_userName = User_.userName.id;
    private final static int __ID_password = User_.password.id;
    private final static int __ID_privileges = User_.privileges.id;
    private final static int __ID_userType = User_.userType.id;
    private final static int __ID_isActive = User_.isActive.id;
    private final static int __ID_image = User_.image.id;
    private final static int __ID_branchId = User_.branchId.id;
    private final static int __ID_waiterId = User_.waiterId.id;
    private final static int __ID_kitchenId = User_.kitchenId.id;
    private final static int __ID_deliveryId = User_.deliveryId.id;

    public UserCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, User_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(User entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(User entity) {
        ToOne<Waiter> waiter = entity.waiter;
        if(waiter != null && waiter.internalRequiresPutTarget()) {
            Cursor<Waiter> targetCursor = getRelationTargetCursor(Waiter.class);
            try {
                waiter.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<Kitchen> kitchen = entity.kitchen;
        if(kitchen != null && kitchen.internalRequiresPutTarget()) {
            Cursor<Kitchen> targetCursor = getRelationTargetCursor(Kitchen.class);
            try {
                kitchen.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        ToOne<Delivery> delivery = entity.delivery;
        if(delivery != null && delivery.internalRequiresPutTarget()) {
            Cursor<Delivery> targetCursor = getRelationTargetCursor(Delivery.class);
            try {
                delivery.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String email = entity.email;
        int __id1 = email != null ? __ID_email : 0;
        String userName = entity.userName;
        int __id2 = userName != null ? __ID_userName : 0;
        String password = entity.password;
        int __id3 = password != null ? __ID_password : 0;
        String privileges = entity.privileges;
        int __id4 = privileges != null ? __ID_privileges : 0;
        byte[] image = entity.image;
        int __id7 = image != null ? __ID_image : 0;

        collect430000(cursor, 0, PUT_FLAG_FIRST,
                __id1, email, __id2, userName,
                __id3, password, __id4, privileges,
                __id7, image, 0, null,
                0, null);

        String branchId = entity.branchId;
        int __id8 = branchId != null ? __ID_branchId : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                __id8, branchId, 0, null,
                0, null, 0, null,
                __ID_waiterId, entity.waiter.getTargetId(), __ID_kitchenId, entity.kitchen.getTargetId(),
                __ID_deliveryId, entity.delivery.getTargetId(), __ID_userType, entity.userType,
                __ID_isActive, entity.isActive ? 1 : 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        attachEntity(entity);
        checkApplyToManyToDb(entity.orders, Order.class);
        checkApplyToManyToDb(entity.notifications, Notification.class);
        checkApplyToManyToDb(entity.logs, LogEvent.class);
        checkApplyToManyToDb(entity.notificationMessages, NotificationMessage.class);
        return __assignedId;
    }

    private void attachEntity(User entity) {
        // Transformer will create __boxStore field in entity and init it here:
        // entity.__boxStore = boxStoreForEntities;
    }

}
