
package com.irestaurant.iPortalAPI.objectbox.model;

import com.irestaurant.iPortalAPI.objectbox.model.WaiterCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Waiter". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Waiter_ implements EntityInfo<Waiter> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Waiter";

    public static final int __ENTITY_ID = 36;

    public static final Class<Waiter> __ENTITY_CLASS = Waiter.class;

    public static final String __DB_NAME = "Waiter";

    public static final CursorFactory<Waiter> __CURSOR_FACTORY = new Factory();

    @Internal
    static final WaiterIdGetter __ID_GETTER = new WaiterIdGetter();

    public final static Waiter_ __INSTANCE = new Waiter_();

    public final static io.objectbox.Property<Waiter> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Waiter> name =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "name");

    public final static io.objectbox.Property<Waiter> phoneNumber =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "phoneNumber");

    public final static io.objectbox.Property<Waiter> totalOrders =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, int.class, "totalOrders");

    public final static io.objectbox.Property<Waiter> image =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, byte[].class, "image");

    public final static io.objectbox.Property<Waiter> isActive =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, boolean.class, "isActive");

    public final static io.objectbox.Property<Waiter> branchId =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, String.class, "branchId");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Waiter>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        name,
        phoneNumber,
        totalOrders,
        image,
        isActive,
        branchId
    };

    public final static io.objectbox.Property<Waiter> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Waiter> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Waiter>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Waiter> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Waiter> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Waiter> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class WaiterIdGetter implements IdGetter<Waiter> {
        @Override
        public long getId(Waiter object) {
            return object.id;
        }
    }

}
