# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://157.250.205.92:3306/portal_db?createDatabaseIfNotExist=true
spring.datasource.username=wbuser
spring.datasource.password=bP^t9F#78b4$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Application Configuration
server.port=2510
spring.application.name=iPortalAPI
spring.servlet.multipart.enabled=true
#server.servlet.context-path=/

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Reset token minutes
iPortalApi.resetToken=15
#iPortalApi.syncDbPath=/var/objectbox-sync/objectbox
iPortalApi.syncDbPath=C:\\Data\\Freelancing\\iRestaurant\\App\\Prod\\iPortalAPI-Prod\\iPortalAPI\\src\\main\\resources\\iRestaurant-db
iPortalApi.syncServerUrl=ws://157.250.205.92:9999
#ws://127.0.0.1:9999
iPortalApi.syncSharedSecret=my_shared_secret

# Token
iPortalApi.jwtSecret= ====#=====&=1====^==h=BXzK15e%=S1#i$^===F==2==A===$==l=X==/==@==
iPortalApi.jwtExpirationMs=86400000

# Springwolf Configuration

# 1. Enable full Springwolf core logging
logging.level.io.github.springwolf=DEBUG

# 2. Specifically log message publishing and STOMP adapter activity
logging.level.io.github.springwolf.core.asyncapi.DefaultAsyncApiService=TRACE
logging.level.io.github.springwolf.stomp=DEBUG

# 3. (Optional) Log Spring's internal messaging for deep troubleshooting
logging.level.org.springframework.messaging=DEBUG

# Enable the publishing feature in the UI
springwolf.ui.publishing.enabled=true
springwolf.plugin.stomp.publishing.enabled=true
# Required: Use fully qualified names for the payloads
springwolf.use-fqn=true

springwolf.enabled=true
springwolf.docket.info.title=iPortalAPI WebSocket Documentation
springwolf.docket.info.version=1.0.0
springwolf.docket.base-package=com.irestaurant.iPortalAPI
springwolf.docket.servers.stomp-server.url=ws://157.250.205.92:2510/ws
springwolf.docket.servers.stomp-server.host=157.250.205.92
springwolf.docket.servers.stomp-server.protocol=stomp

springwolf.plugin.stomp.scanner.stomp-send-to.enabled=true
springwolf.plugin.stomp.scanner.stomp-message-mapping.enabled=true
springwolf.plugin.stomp.scanner.stomp-send-to-user.enabled=true

# Email Configuration
iPortalApi.email.from=info@iqtech-sys.com
iPortalApi.email.subject=Password Reset Request
iPortalApi.email.text=To reset your password, click the link below:
iPortalApi.email.resetLink=http://157.250.205.92:2510/reset-password?token=

# Spring Mail Configuration (REQUIRED for JavaMailSender)
# Replace these with your actual SMTP server details
spring.mail.host=mail.iqtech-sys.com
spring.mail.port=8889
spring.mail.username=info@iqtech-sys.com
spring.mail.password=q!w@e#r$qwer1234
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Actuator / Monitoring Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.tracing.sampling.probability=1.0

# Zipkin server
#management.zipkin.tracing.endpoint=http://157.250.205.92:9411/api/v2/spans
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# Enable tracing and set sampling to 100% (for development)
management.tracing.sampling.probability=1.0
# Include Trace ID and Span ID in logs automatically
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
