name: Deploy iPortal Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "target/*.jar"
          target: ${{ secrets.APP_DIR }}

      - name: Activate release
          uses: appleboy/ssh-action@v1.0.3
          with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
               set -e
               
               cd ${{ secrets.APP_DIR }}
               
               NEW_JAR=$(ls target/*.jar | head -n 1)
               
               if [ -f app.jar ]; then
               
                 mv app.jar app-prev.jar
                 
               fi
               
               mv $NEW_JAR app.jar
               
               if ! sudo systemctl restart $SERVICE; then               
               
                   echo "Deployment failed, rolling back..."
                   
                   mv app-prev.jar app.jar
                   
                   sudo systemctl restart $SERVICE
                   
                   exit 1
                   
               fi