name: Deploy iPortal Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "target/*.jar"
          target: ${{ secrets.APP_DIR }}

      - name: Activate release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e

            cd ${{ secrets.APP_DIR }}

            NEW_JAR=$(ls target/*.jar | head -n 1)
            SERVICE=${{ secrets.SERVICE_NAME }}
            JAR_FILE_NAME=${{ secrets.JAR_FILE_NAME }}

            if [ -f $JAR_FILE_NAME ]; then
              mv $JAR_FILE_NAME app-prev.jar
            fi

            mv $NEW_JAR $JAR_FILE_NAME

            if ! sudo systemctl restart $SERVICE; 
            then
              echo "Deployment failed, rolling back..."

              mv app-prev.jar $JAR_FILE_NAME
              sudo systemctl restart $SERVICE

              exit 1
            fi

            sudo systemctl daemon-reload
            rm -rf ${{ secrets.APP_DIR }}/target